---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  tasks:

    - name: build test image
      command: >-
        podman build -t molecule-test-image molecule-test-image

    - name: start test containers
      command: >-
        podman run -d --init --rm
        --name molecule-{{ item.name }}-{{ idx }}
        --hostname molecule-{{ item.name }}.example.com
        -p {{ 2000 + idx }}:22
        molecule-test-image
      register: server
      loop: "{{ molecule_yml.platforms }}"
      loop_control:
        index_var: idx

    - block:
        - name: Populate instance config dict
          set_fact:
            instance_conf_dict: {
              'instance': "{{ item.item.name }}",
              'address': "localhost",
              'user': "root",
              'port': "{{ 2000 + idx }}",
              'identity_file': "molecule-test-image/molecule_rsa", }
          loop: "{{ server.results }}"
          loop_control:
            index_var: idx
          register: instance_config_dict

        - name: Convert instance config dict to a list
          set_fact:
            instance_conf: "{{ instance_config_dict.results | map(attribute='ansible_facts.instance_conf_dict') | list }}"

        - name: Dump instance config
          copy:
            content: |
              # Molecule managed

              {{ instance_conf | to_yaml }}
            dest: "{{ molecule_instance_config }}"
