---
name: 'Run tests'

on:
  push:

jobs:
  unit_tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install python dependencies
        run: |
          pip install flake8 pytest

      - name: Run pytest
        run: |
          PYTHONPATH=$PWD pytest -v tests/unit

  molecule:
    name: Run molecule tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ansible_collections/moc/mailman

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install python dependencies
        run: |
          pip install molecule

      - name: Run molecule
        run: |
          cd ansible_collections/moc/mailman
          chmod 600 molecule/default/molecule-test-image/molecule_rsa
          molecule --version
          molecule test
